[workspace]
authors = ["Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>"]
channels = ["conda-forge"]
name = "dra-ttt-course-pixi-mwe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jupyter = "jupyter lab --no-browser"

[dependencies]
r-base = ">=4.5.2,<4.6"
r-ggplot2 = ">=4.0.1,<5"
xeus-r = ">=0.8.1,<0.9"
jupyterlab = ">=4.5.1,<5"
